### ISSUE TITLE
Izrada UML dijagrama klasa

### ISSUE THREAD

**Issue by akudelic1** [AIR-FOI-HR/AIR1916#10]

**Comment by sdrvoderi** [comment]
Kreiran je inicijalni dijagram klasa na kojemu se mogu vidjeti sve potrebne klase za prikaz publikacije, filtriranje publikacija, pretragu publikacija te se može vidjeti sučelje (interface) koji će se koristiti za modularni dio aplikacije te možemo vidjeti klase od 3 modula.
