### ISSUE TITLE
Odlazak na konzultacije kod mentora

### ISSUE THREAD

**Issue by akudelic1** [AIR-FOI-HR/AIR1916#12]

**Comment by akudelic1** [comment]
Na ovim konzultacijama smo dobili bolji uvid u to kako bi sprintevi trebali izgledati. Dogovorene su neke od osnovnih funkcionalnosti s mentorom te nam je pobliže objašnjen način na koji bi mogli implementirati određene funkcionalnosti poput logina (osnovnog -AAI@edu.hr i modularnog - pin, uzorak, otisak prsta). Također, dogovorili smo smjernice za razvoj same aplikacije te dobili "hintove" vezane za ERA model.

**Comment by boristomas** [comment]
wow
