### ISSUE TITLE
2. Pregled literature

### ISSUE THREAD

**Issue by akudelic1** [AIR-FOI-HR/AIR1916#23]

**Comment by mlipovaca** [comment]
Napravljen prikaz literature (publikacije) na zaslonu, tj. dohvaća se putem WebServisa i LINQ query-a koji dalje prosljeđuje u aplikaciju potrebne atribute za Publikacije kojim zatim prikazujemo u obliku Liste sa path slike koji se dohvaćaju online, Naziv publikacije, Autor publikacije, Izdavac publikacije te Godina izdanja publikacije
