### ISSUE TITLE
2.4 Detaljne informacije

### ISSUE THREAD

**Issue by akudelic1** [AIR-FOI-HR/AIR1916#27]

**Comment by mmacinkov** [comment]
Kreiran je novi xaml file BookInfo u kojem je implementiran prikaz informacija o pojedinoj knjizi. U kontroleru za publikacije kreiran je upit koji dohvaća informacije o pojedinoj knjizi putem id-a. Kasnije se isti koristi pri implementaciji za dohvat knjige. 
U klasi publikacije dodani su novi atributi koji omogućuju prikaz stanja i kopija  raznih knjiga.
