### ISSUE TITLE
2.6 Rezerviranje knjige

### ISSUE THREAD

**Issue by akudelic1** [AIR-FOI-HR/AIR1916#29]

**Comment by mmacinkov** [comment]
Omogućen je odabir kopije pojedine publikacije i uvid u stanje iste.  Ukoliko je publikacija slobodna moguće ju je rezervirati, rezervacija traje 5 dana nakon čega ista ističe ukoliko se knjiga ne posudi te se njeno stanje vraća u slobodno ako nije posudena. Ako je status knjige rezervirano, omogućen je uvid u trajanje rezervacije pri čemu korisnik točno zna do kada treba rezerviranu publikaciju podići.
