### ISSUE TITLE
3.1 Prekidanje rezervacije

### ISSUE THREAD

**Issue by akudelic1** [AIR-FOI-HR/AIR1916#31]

**Comment by sdrvoderi** [comment]
Izrađena je mogućnost prekidanja rezervacije tako da korisnik ode na prikaz svoje povijesti (rezervacije/posudbe) te odabere neku od trenutno aktivnih rezervacija (zelena pozadina) pritisne na nju te potvrdi prekidanje rezervacije čime je kopija opet slobodna za rezerviranje.
Izmijenjeni je kontroler za rezerviranje tako da se dodaje novo stavka u bazu umjesto da se izmjenjuje stara tako da se može prema stavkama stanja neke kopije dobiti povijest.
