### ISSUE TITLE
4.1 Podsjetnik o slobodnoj knjizi

### ISSUE THREAD

**Issue by akudelic1** [AIR-FOI-HR/AIR1916#34]

**Comment by sdrvoderi** [comment]
Napravljena je azure notification hub registracija za korisnike android mobilnih telefona, napravljena je azure funkcija koja prema tag-u korisnika koji je ujedno i njegov id mobitela, šalje push notifikaciju o oslobođenju njegovog favorita, također dodan je poziv te azure funkcije u dio prekida rezervacije tako da se kod svakog prekida rezervacije pronađu korisnici kojima je ta rezervacija favorit te se im pošalje notifikaciju
