### ISSUE TITLE
4.2 Notifikacija o isteku rezervacije ili roka vraćanja knjige

### ISSUE THREAD

**Issue by akudelic1** [AIR-FOI-HR/AIR1916#35]

**Comment by sdrvoderi** [comment]
Napravljena je azure funkcija (time trigger) koja se aktivira svaki dan u 8 sati te provjeri postoje li publikacije čija posudba ili rezervacija vrijedi još samo taj dan. Ako postoji takva publikacija šalje se mail korisniku da ima rezervacije/posube koje mu ističu.
