### ISSUE TITLE
Izrada korisničkih zahtjeva

### ISSUE THREAD

**Issue by akudelic1** [AIR-FOI-HR/AIR1916#4]

**Comment by sdrvoderi** [comment]
Kreirana mapa "Dokumentacija" sa datotekom "Tehnička Dokumentacija". Mapa "Dokumentacija" sadržavat će sve datoteke dokumentacije te sve ostale datoteke vezane uz dokumentaciju. Datoteka "Tehnička Dokumetacija" u ovoj verziji sadrži listu funkcionalnosti (korisničke zahtjeve) te će se ova datoteka u budućnosti koristiti za svu tehničku dokumentaciju. 

U tablici su kreirane podjele korisničkih zahtjeva u skupine te svaka skupina sadržava dijelove koji se odnose na nju. Prva skupina prijava sadržava sve funkcionalnosti vezane uz prijavu, a to su prijava putem korisničkog imena i lozinke te brze načine prijave kao što su PIN, otisak i uzorak. Brzi načini označeni su kao modularni, a korisničko ime i lozinka nije iz razloga što će taj način biti uvijek dostupan korisniku kao sigurna opcija u slučaju da nema čitač otiska ili se želi prijaviti sa drugog mobitela. Ostali dijelovi nemaju nikakve posebne napomene.
