### ISSUE TITLE
Posudba knjige putem NFC-a

### ISSUE THREAD

**Issue by akudelic1** [AIR-FOI-HR/AIR1916#69]

**Comment by mlipovaca** [comment]
Implementacija posuđivanja kopije publikacije putem NFC-a na način da se skenira Tag od "virtualne" publikacije te se time očitava Tag u obliku text-a koji se prenosi na aplikaciju te se u bazi podatak promjenjuje stanje publikacije u Posuđeno za tu kopiju i osvježava prikaz
