### ISSUE TITLE
Izrada dijagrama korištenja

### ISSUE THREAD

**Issue by akudelic1** [AIR-FOI-HR/AIR1916#7]

**Comment by sdrvoderi** [comment]
Izrađen je UseCase dijagram aplikacije FOI knjižnica te je dijagram dodan u tehničku dokumentaciju kako bi se pobliže prikazale mogućnosti buduće aplikacije. Druga svrha izrađenog dijagrama korištenja je mogućnost referenciranja na isti prilikom izrade ostalih dijagrama koji će se raditi u budućnosti. U dijagramu se također može vidjeti da će aplikacija od vanjskih servisa koristiti servis od kompanije Srce (Sveučilište u Zagrebu Sveučilišni računski centar) , a taj servis je AAI@EduHR koji će biti detaljnije objašnjen prilikom izrade prijave. Druga stvar koju je potrebno napomenuti je da na dijagramu slučaja korištenja nema ovisnosti slučajeva prema prijavi, što će u stvarnosti postojati, ali je zbog preglednosti dijagrama uklonjena i stavljena kao napomena u dokumentaciji.
