### ISSUE TITLE
3.3 Prikaz povijesti posudbi

### ISSUE THREAD

**Issue by akudelic1** [AIR-FOI-HR/AIR1916#73]

**Comment by sdrvoderi** [comment]
Napravljen je prikaz korisnikove povijesti posudba i rezervacija te prikaz vraćenih publikacija. Povijest je podijeljena u tri listview-a od kojih je svaki za jednu vrstu. Također napravljen je prikaz aktivnosti neke stavke pomoću boje pa se tako mogu lakše uočiti rezervacije i posudbe koje su još aktivne od onih koje više to nisu.
