### ISSUE TITLE
3.5 Pregled i otkazivanje rezervacija

### ISSUE THREAD

**Issue by akudelic1** [AIR-FOI-HR/AIR1916#75]

**Comment by sdrvoderi** [comment]
Pregled rezervacija je napravljen u sklopu issue-a #73 3.3 Prikaz povijesti posudbi jer je u tome dijelu napravljen kompletni prikaz povijesti posudba/rezervacija korisnika.
Otkazivanje rezervacija napravljeno je u sklopu issue-a #73 3.1 Prekidanje rezervacije gdje je dodana mogućnost otkazivanja trenutno aktivnih rezervacija korisnika.
