### ISSUE TITLE
Dodavanje/Promjena Pin-a

### ISSUE THREAD

**Issue by mivanic9** [AIR-FOI-HR/AIR1916#88]
Dodavanje mogućnosti unosa Pin lozinke. Isto tako mogućnost promjene Pin lozinke.

**Comment by akudelic1** [comment]
Ostvarena je funkcionalnost dodavanja i izmjene pina. Pin se može dodati prilikom inicijalnog postavljanja a nakon toga se može mijenjati po želji. Također, pin sadrži 4 znaka.
